GET http://localhost:5000/usuarios/carrito
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiY29ycmVvIjoibHVjaWFwQGp1ZWdvc3hkLmNvbSIsInJvbCI6IlVTRVIiLCJpYXQiOjE3NTI1Mjg1OTIsImV4cCI6MTc1MjUzMjE5Mn0.R49eCn0sbM2ifQXer7h2E2rXR2zi-qB7cjfX-HH7IMM
Content-Type: application/json
